name: Acceptance Tests

on: [push]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Check out oats
        uses: actions/checkout@v4
        with:
          repository: arukiidou/oats
          ref: da64b972780f41f420f51b6201df7076c9e3a4cc
          path: oats
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: oats/go.sum
      - name: Build Image for integration tests
        run: ./build-lgtm.sh
      - name: Run acceptance tests
        run: ./scripts/run-acceptance-tests.sh
      - name: upload log file
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: docker-compose.log
          path: oats/yaml/build/**/output.log
